# Generated by Django 4.2.10 on 2025-05-08 06:01

from django.db import migrations, models
import django.db.models.deletion
import summarizer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Example Set',
                'verbose_name_plural': 'Example Sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to=summarizer.models.summary_upload_path)),
                ('project_type', models.CharField(max_length=50)),
                ('pdf_password', models.CharField(blank=True, max_length=100)),
                ('summary_text', models.TextField(blank=True)),
                ('original_text', models.TextField(blank=True)),
                ('corrected_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('corrected', 'Corrected'), ('error', 'Error')], default='pending', max_length=20)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medical Summary',
                'verbose_name_plural': 'Medical Summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('missing_section', 'Missing Section'), ('extra_section', 'Extra Section'), ('missing_content', 'Missing Content'), ('incorrect_information', 'Incorrect Information'), ('removed_content', 'Removed Content')], max_length=50)),
                ('section', models.CharField(max_length=100)),
                ('original_text', models.TextField(blank=True)),
                ('corrected_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='summarizer.summary')),
            ],
            options={
                'verbose_name': 'Error Pattern',
                'verbose_name_plural': 'Error Patterns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to=summarizer.models.example_upload_path)),
                ('summary_file', models.FileField(upload_to=summarizer.models.example_upload_path)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('example_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='summarizer.exampleset')),
            ],
            options={
                'verbose_name': 'Document Example',
                'verbose_name_plural': 'Document Examples',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
