# Generated by Django 4.2.10 on 2025-05-14 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={},
        ),
        migrations.AddField(
            model_name='summary',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='summary',
            name='corrected_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='original_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='pdf_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='project_type',
            field=models.CharField(choices=[('ah', 'AH PLLC'), ('tlc', 'TLC S PLLC'), ('sa', 'SA PLLC'), ('lw', 'LW PLLC')], max_length=10),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
