# Generated by Django 4.2.10 on 2025-06-01 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0002_alter_summary_options_summary_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['-created_at'], 'verbose_name': 'Medical Summary', 'verbose_name_plural': 'Medical Summaries'},
        ),
        migrations.AddField(
            model_name='summary',
            name='batch_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Groups files uploaded together'),
        ),
        migrations.AddField(
            model_name='summary',
            name='batch_name',
            field=models.CharField(blank=True, help_text='Name for the batch of files', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='is_batch',
            field=models.BooleanField(default=False, help_text='True if this was part of a multi-file upload'),
        ),
    ]
